server:
  port: ${providerServicePort}

spring:
  application:
    name: ${providerModuleName}
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:${eurekaServerPort}/eureka/


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: ${basePackage}.mapper
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true

pagehelper:
  reasonable: true
  params: count=countSql
  auto-runtime-dialect: true
