mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.xi.quick.codegenerator.mapper
  configuration:
    cache-enabled: false
    lazy-loading-enabled: false
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: false
    default-executor-type: simple
    default-statement-timeout: 25000
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    call-setters-on-nulls: true
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quick?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=true&useServerPrepStmts=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

dollar: $

generator:
  database-name: quick
  encoding: UTF-8
  table-name-match-regex: '(?<=dm_uba_).*(?=_tmp)'
  paths:
    template: /Workspace/github.com/java/code-generator/templates/spring-cloud-kt/templates/
    out: /Workspace/github.com/java/code-generator/templates/out/
  files:
    ignore: include/
    aggregate: static/index.html
    copy: resources/css/, common.js, .gitignore

  columns:
    base:
      column-name-set: is_deleted, create_time, update_time
      table-name: user
    not-required:
      - column-name-set: create_time, update_time
    img-url:
      - column-name-set: photo
#    video-url:
#    doc-url:
#    page-url:
#    other-url:
    content:
      - column-name-set: introduction, remark

    select:
      - column-name-set: status
        table-name: multi_pk
        options:
          - value: 1
            text: 正常
          - value: 2
            text: 提高
          - value: 3
            text: 起飞
    fk-select:
      - column-name-set: user_type_id
        fk:
          foreign-table-name: user_type
          value-column-name: id
          text-column-name: user_type_name
    valid-status:
      - column-name-set: is_deleted
        status:
          valid: 0
          invalid: 1

  # 公共自定义属性
  common-properties:
    projectName: quick-cloud-auto
    projectShortName: quick
    projectGroup: org.xi
    projectVersion: 1.0-SNAPSHOT

    basePackage: org.xi.quick
    baseCommonPackage: org.xi.common

    commonModuleName: quick-common
    modelModuleName: quick-model
    providerModuleName: quick-provider
    adminApiModuleName: quick-admin-api
    eurekaServerModuleName: quick-eureka-server

    providerModuleApplicationName: QuickProviderApplication
    adminModuleApplicatioName: QuickAdminApplication
    eurekaServerModuleApplicatioName: QuickEurekaServerApplication

    eurekaServerPort: 8770
    providerServicePort: 8810
    adminServicePort: 8820

    baseApiPath: http://localhost:8820

    author: 郗世豪（rarexixi@outlook.com）
    codeVersion: 1.0
    javaSrc: src/main/java
    javaTestSrc: src/test/java
    resourcesSrc: src/main/resources

  # 获取数据映射关系
  data-type-map:
    tinyint: Integer
    smallint: Integer
    int: Integer
    bigint: Long
    float: Float
    double: Double
    decimal: BigDecimal
    numeric: BigDecimal
    bit: Boolean
    character: Character
    varchar: String
    char: String
    text: String
    date: Date
    datetime: Date
    timestamp: Date