server:
  port: 8810

spring:
  application:
    name: ${providerModuleName}
  datasource:
    url: ${dbUrl}
    username: ${dbUsername}
    password: ${dbPassword}
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: ${basePackage}.mapper

dubbo:
  application:
    id: ${providerModuleName}
    name: ${providerModuleName}
    owner:
  protocol:
    id: dubbo
    name: dubbo
  provider:
    group: ${dubboServiceGroup}
    version: ${dubboServiceVersion}
  registry:
    id: ${dubboServiceProtocol}
    protocol: ${dubboServiceProtocol}
    address: ${dubboRegistryAddress}
    group: dubbo # 对应dubbo-admin的dubbo.properties中的dubbo.registry.group=dubbo，默认是dubbo，不一致的话dubbo-admin上不会显示注册的服务
    version: ${dubboServiceVersion}
    client: curator
  scan:
    base-packages: ${basePackage}.api
